export const GET_CITIES_FROM = 'GET_CITIES_FROM';
export const GET_NEW_CITIES_FROM = 'GET_NEW_CITIES_FROM';
export const GET_CITIES_TO = 'GET_CITIES_TO';
export const GET_NEW_CITIES_TO = 'GET_NEW_CITIES_TO';
export const GET_INFO_FOR_TICKET = 'GET_INFO_FOR_TICKET';
