export const GET_EXCURSIONS_CITY_START = 'GET_EXCURSIONS_CITY_START';
export const GET_EXCURSIONS_CITY_SUCCESS = 'GET_EXCURSIONS_CITY_SUCCESS';
export const GET_EXCURSIONS_CITY_ERROR = 'GET_EXCURSIONS_CITY_ERROR';

export const POST_EXCURSION_BOOKING_START = 'POST_EXCURSION_BOOKING_START';
export const POST_EXCURSION_BOOKING_SUCCESS = 'POST_EXCURSION_BOOKING_SUCCESS';
export const POST_EXCURSION_BOOKING_ERROR = 'POST_EXCURSION_BOOKING_ERROR';
