export const GET_CITIES_LOCATION_LOADER = 'GET_CITIES_LOCATION_LOADER';
export const GET_CITIES_LOCATION_SUCCESS = 'GET_CITIES_LOCATION_SUCCESS';
export const GET_CITIES_LOCATION_ERROR = 'GET_CITIES_LOCATION_ERROR';
export const GET_CITIES_LOCATION_SAGA = 'GET_CITIES_LOCATION_SAGA';

export const GET_TICKETS_PRICE_LOADER = 'GET_TICKETS_PRICE_LOADER';
export const GET_TICKETS_PRICE_SUCCESS = 'GET_TICKETS_PRICE_SUCCESS';
export const GET_TICKETS_PRICE_ERROR = 'GET_TICKETS_PRICE_ERROR';
export const GET_TICKETS_PRICE_SAGA = 'GET_TICKETS_PRICE_SAGA';

export const GET_AIRLINE_NAME_START = 'GET_AIRLINE_NAME_START';
export const GET_AIRLINE_NAME_SUCCESS = 'GET_AIRLINE_NAME_SUCCESS';
export const GET_AIRLINE_NAME_ERROR = 'GET_AIRLINE_NAME_ERROR';

export const SET_CURRENT_TICKET_START = 'SET_CURRENT_TICKET_START';
export const SET_CURRENT_TICKET_SUCCESS = 'SET_CURRENT_TICKET_SUCCESS';
export const SET_CURRENT_TICKET_ERROR = 'SET_CURRENT_TICKET_ERROR';

export const FIND_CURRENT_TICKET_START = 'FIND_CURRENT_TICKET_START';
export const FIND_CURRENT_TICKET_SUCCESS = 'FIND_CURRENT_TICKET_SUCCESS';
export const FIND_CURRENT_TICKET_ERROR = 'FIND_CURRENT_TICKET_ERROR';
