export const GET_USER_PERSONAL_TICKET_LIST = 'GET_USER_PERSONAL_TICKET_LIST';
export const GIVE_USER_PERSONAL_TICKET_LIST = 'GIVE_USER_PERSONAL_TICKET_LIST';
export const DELETE_USER_PERSONAL_TICKET_LIST = 'DELETE_USER_PERSONAL_TICKET_LIST';
export const SORT_USER_PERSONAL_TICKET_LIST = 'SORT_USER_PERSONAL_TICKET_LIST';
