export const GET_USER_IP_LOADER = 'GET_USER_IP_LOADER';
export const GET_USER_IP_SUCCESS = 'GET_USER_IP_SUCCESS';
export const GET_USER_IP_ERROR = 'GET_USER_IP_ERROR';
export const GET_USER_IP_SAGA = 'GET_USER_IP_SAGA';

export const AUTH_USER_START = 'AUTH_USER_START';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

export const REG_USER_START = 'REG_USER_START';
export const REG_USER_SUCCESS = 'REG_USER_SUCCESS';
export const REG_USER_ERROR = 'REG_USER_ERROR';

export const LOGOUT_USER_START = 'LOGOUT_USER_START';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const CHECK_AUTH_START = 'CHECK_AUTH_START';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_ERROR = 'CHECK_AUTH_ERROR';

export const GET_USER_EXCURSIONS_START = 'GET_USER_EXCURSIONS_START';
export const GET_USER_EXCURSIONS_SUCCESS = 'GET_USER_EXCURSIONS_SUCCESS';
export const GET_USER_EXCURSIONS_ERROR = 'GET_USER_EXCURSIONS_ERROR';

export const DELETE_USER_BOOKING_START = 'DELETE_USER_BOOKING_START';
export const DELETE_USER_BOOKING_SUCCESS = 'DELETE_USER_BOOKING_SUCCESS';
export const DELETE_USER_BOOKING_ERROR = 'DELETE_USER_BOOKING_ERROR';
export const NEW_USER_PASS = 'NEW_USER_PASS';
